# -*- coding: utf-8 -*-
"""Reto_12_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BQL7qlp4M_A3ZCUj3EHltYQa00MBZus
"""

with open("mbox-short.txt", "r") as archivo: # Abrimos el archivo con with
    contenido = archivo.read() # Variable que lee el archivo
    num_vocales = 0 # contador para vocales
    num_consonantes = 0 # Contador para consonantes
    for letra in contenido: # Ciclo for que recorre la lista
      if letra.lower() in "aeiouáéíóú":
        num_vocales += 1 # busca si hay vocal en minuscula o mayuscula, con tilde o sin ella y suma uno al contador
      elif letra.lower() in "bcdfghjklmnñpqrstvwxyz":
        num_consonantes += 1 # busca si hay consontate en minuscula o mayuscula y suma uno al contador
    print("El número de vocales es: " +str(num_vocales)) #vocales
    print("El número de consonantes es: " +str(num_consonantes)) # consonantes

from collections import Counter # Importamos libreria para contar
with open("mbox-short.txt", "r") as archivo: # Abrimos el archivo con with
    contenido = archivo.read() # Variable que lee el archivo
    contenido = contenido.split() # separa cada elemento por palabras, considerando los espacios entre ellas
    palabras = Counter(contenido).most_common(50) # agtega a la variable palabra, la lista de las 50 que mas aparecen
    m=0 #contador
    print("Las 50 palabras que más se repiten son: ")
    for i in palabras: #ciclo for para imprimir en lista
      m += 1 # contador para enumerar palabras
      print("Palabra número " +str(m)+ ": " +str(i) ) #50 palabra que más se repiten